// 装备数据定义文件
// 根据 ADND 2E 规则实现

// 装备接口定义
export interface Equipment {
  id: string;
  name: string;
  nameEn?: string; // 英文名
  price: number; // 价格（统一使用GP作为基准）
  weight: number; // 重量（磅）
  category: string; // 类别
  description?: string; // 描述
}

// 武器特殊属性
export interface Weapon extends Equipment {
  size: 'S' | 'M' | 'L'; // 尺寸
  type: 'B' | 'P' | 'S' | 'P/B' | 'P/S'; // 类型：钝击/穿刺/挥砍
  speed: number; // 速率
  damageS: string; // 对小型/中型生物伤害
  damageL: string; // 对大型生物伤害
  rateOfFire?: string; // 射速（远程武器）
  range?: { short: number; medium: number; long: number }; // 射程
  versatile?: {
    // 多功能武器（如混种剑可单手或双手使用）
    '1H': { speed: number; damageS: string; damageL: string };
    '2H': { speed: number; damageS: string; damageL: string };
  };
}

// 护甲特殊属性
export interface Armor extends Equipment {
  ac: number; // 防御等级
  armorType: 'light' | 'medium' | 'heavy' | 'shield'; // 护甲类型
}

// 货币转换率（以GP为基准）
export const CURRENCY_RATES = {
  CP: 0.01, // 1 CP = 0.01 GP
  SP: 0.1, // 1 SP = 0.1 GP
  EP: 0.5, // 1 EP = 0.5 GP
  GP: 1, // 1 GP = 1 GP
  PP: 5, // 1 PP = 5 GP
};

// 货币转换函数
export function convertToGP(amount: number, currency: keyof typeof CURRENCY_RATES): number {
  return amount * CURRENCY_RATES[currency];
}

// 格式化价格显示
export function formatPrice(gp: number): string {
  if (gp >= 1) return `${gp}gp`;
  if (gp >= 0.5) return `${gp * 2}ep`;
  if (gp >= 0.1) return `${gp * 10}sp`;
  return `${gp * 100}cp`;
}

// 装备分类
export const EQUIPMENT_CATEGORIES = [
  { id: 'clothing', name: '衣物', nameEn: 'Clothing' },
  { id: 'food-lodging', name: '日常食宿', nameEn: 'Daily Food and Lodging' },
  { id: 'household', name: '家庭供应', nameEn: 'Household Provisioning' },
  { id: 'transport', name: '运输', nameEn: 'Transport' },
  { id: 'animals', name: '动物', nameEn: 'Animals' },
  { id: 'services', name: '服务', nameEn: 'Services' },
  { id: 'tack', name: '坐骑装备', nameEn: 'Tack and Harness' },
  { id: 'miscellaneous', name: '其他装备', nameEn: 'Miscellaneous Equipment' },
  { id: 'armor', name: '护甲', nameEn: 'Armor' },
  { id: 'weapons', name: '武器', nameEn: 'Weapons' },
];

// ==================== 衣物 (Clothing) ====================
const clothingEquipment: Equipment[] = [
  { id: 'belt', name: '皮质腰带', nameEn: 'Belt', price: convertToGP(3, 'SP'), weight: 0.1, category: 'clothing' },
  { id: 'boots-riding', name: '马靴', nameEn: 'Riding Boots', price: 3, weight: 2, category: 'clothing' },
  { id: 'boots-soft', name: '软靴', nameEn: 'Soft Boots', price: 1, weight: 1, category: 'clothing' },
  { id: 'breeches', name: '马裤', nameEn: 'Breeches', price: 2, weight: 1, category: 'clothing' },
  { id: 'cap-hat', name: '帽子', nameEn: 'Cap/Hat', price: convertToGP(1, 'SP'), weight: 0.1, category: 'clothing' },
  {
    id: 'cloak-cloth',
    name: '优质布料斗篷',
    nameEn: 'Cloak (Good cloth)',
    price: convertToGP(8, 'SP'),
    weight: 2,
    category: 'clothing',
  },
  { id: 'cloak-fur', name: '精制毛皮斗篷', nameEn: 'Cloak (Fine fur)', price: 50, weight: 3, category: 'clothing' },
  { id: 'girdle', name: '束腰', nameEn: 'Girdle', price: 3, weight: 1, category: 'clothing' },
  { id: 'gloves', name: '手套', nameEn: 'Gloves', price: 1, weight: 0.1, category: 'clothing' },
  {
    id: 'gown-common',
    name: '普通礼服',
    nameEn: 'Common Gown',
    price: convertToGP(12, 'SP'),
    weight: 2,
    category: 'clothing',
  },
  { id: 'hose', name: '紧身裤', nameEn: 'Hose', price: 2, weight: 1, category: 'clothing' },
  {
    id: 'knife-sheath',
    name: '小刀鞘',
    nameEn: 'Knife sheath',
    price: convertToGP(3, 'CP'),
    weight: 0.1,
    category: 'clothing',
  },
  {
    id: 'mittens',
    name: '露指手套',
    nameEn: 'Mittens',
    price: convertToGP(3, 'SP'),
    weight: 0.1,
    category: 'clothing',
  },
  { id: 'pin', name: '徽章', nameEn: 'Pin', price: 6, weight: 0.1, category: 'clothing' },
  { id: 'brooch', name: '简朴胸针', nameEn: 'Plain brooch', price: 10, weight: 0.1, category: 'clothing' },
  {
    id: 'robe-common',
    name: '普通长袍',
    nameEn: 'Common Robe',
    price: convertToGP(9, 'SP'),
    weight: 2,
    category: 'clothing',
  },
  { id: 'robe-embroidered', name: '刺绣长袍', nameEn: 'Embroidered Robe', price: 20, weight: 2, category: 'clothing' },
  { id: 'sandals', name: '凉鞋', nameEn: 'Sandals', price: convertToGP(5, 'CP'), weight: 0.5, category: 'clothing' },
  { id: 'sash', name: '系带', nameEn: 'Sash', price: convertToGP(2, 'SP'), weight: 0.1, category: 'clothing' },
  { id: 'shoes', name: '鞋子', nameEn: 'Shoes', price: 1, weight: 1, category: 'clothing' },
  { id: 'silk-jacket', name: '丝绸上衣', nameEn: 'Silk jacket', price: 80, weight: 1, category: 'clothing' },
  { id: 'surcoat', name: '外套', nameEn: 'Surcoat', price: convertToGP(6, 'SP'), weight: 2, category: 'clothing' },
  {
    id: 'sword-scabbard',
    name: '剑鞘、挂钩或挂饰',
    nameEn: 'Sword scabbard',
    price: 4,
    weight: 1,
    category: 'clothing',
  },
  { id: 'tabard', name: '战袍', nameEn: 'Tabard', price: convertToGP(6, 'SP'), weight: 1, category: 'clothing' },
  {
    id: 'toga',
    name: '粗制罩袍',
    nameEn: 'Toga (coarse)',
    price: convertToGP(8, 'CP'),
    weight: 2,
    category: 'clothing',
  },
  { id: 'tunic', name: '衬衣', nameEn: 'Tunic', price: convertToGP(8, 'SP'), weight: 1, category: 'clothing' },
  { id: 'vest', name: '背心', nameEn: 'Vest', price: convertToGP(6, 'SP'), weight: 1, category: 'clothing' },
];

// ==================== 日常食宿 (Daily Food and Lodging) ====================
const foodLodgingEquipment: Equipment[] = [
  {
    id: 'ale',
    name: '麦酒（每加仑）',
    nameEn: 'Ale (per gallon)',
    price: convertToGP(2, 'SP'),
    weight: 8,
    category: 'food-lodging',
  },
  {
    id: 'banquet',
    name: '宴席（每人）',
    nameEn: 'Banquet (per person)',
    price: 10,
    weight: 0,
    category: 'food-lodging',
  },
  { id: 'bread', name: '面包', nameEn: 'Bread', price: convertToGP(5, 'CP'), weight: 0.5, category: 'food-lodging' },
  { id: 'cheese', name: '奶酪', nameEn: 'Cheese', price: convertToGP(4, 'SP'), weight: 0.5, category: 'food-lodging' },
  {
    id: 'room-common',
    name: '普通租房（每月）',
    nameEn: 'Common Room (monthly)',
    price: 20,
    weight: 0,
    category: 'food-lodging',
  },
  {
    id: 'room-poor',
    name: '较差租房（每月）',
    nameEn: 'Poor Room (monthly)',
    price: convertToGP(6, 'SP'),
    weight: 0,
    category: 'food-lodging',
  },
  {
    id: 'wine-common',
    name: '普通酒（每壶）',
    nameEn: 'Common wine (per pitcher)',
    price: convertToGP(2, 'SP'),
    weight: 3,
    category: 'food-lodging',
  },
  {
    id: 'egg',
    name: '鸡蛋或新鲜蔬菜',
    nameEn: 'Egg or vegetables',
    price: convertToGP(1, 'CP'),
    weight: 0.1,
    category: 'food-lodging',
  },
  {
    id: 'grain-stabling',
    name: '饲料与马厩（每日）',
    nameEn: 'Grain and stabling (daily)',
    price: convertToGP(5, 'SP'),
    weight: 0,
    category: 'food-lodging',
  },
  { id: 'honey', name: '蜂蜜', nameEn: 'Honey', price: convertToGP(5, 'SP'), weight: 1, category: 'food-lodging' },
  {
    id: 'inn-common-day',
    name: '普通旅店住宿（每天）',
    nameEn: 'Inn lodging common (daily)',
    price: convertToGP(5, 'SP'),
    weight: 0,
    category: 'food-lodging',
  },
  {
    id: 'inn-poor-day',
    name: '较差旅店住宿（每天）',
    nameEn: 'Inn lodging poor (daily)',
    price: convertToGP(5, 'CP'),
    weight: 0,
    category: 'food-lodging',
  },
  {
    id: 'meat',
    name: '肉食（一顿）',
    nameEn: 'Meat (one meal)',
    price: convertToGP(1, 'SP'),
    weight: 1,
    category: 'food-lodging',
  },
  {
    id: 'meal-good',
    name: '良好伙食（每天）',
    nameEn: 'Good Meals (daily)',
    price: convertToGP(5, 'SP'),
    weight: 0,
    category: 'food-lodging',
  },
  {
    id: 'meal-common',
    name: '普通伙食（每天）',
    nameEn: 'Common Meals (daily)',
    price: convertToGP(3, 'SP'),
    weight: 0,
    category: 'food-lodging',
  },
  {
    id: 'meal-poor',
    name: '较差伙食（每天）',
    nameEn: 'Poor Meals (daily)',
    price: convertToGP(1, 'SP'),
    weight: 0,
    category: 'food-lodging',
  },
  {
    id: 'small-beer',
    name: '劣质啤酒',
    nameEn: 'Small beer',
    price: convertToGP(5, 'CP'),
    weight: 1,
    category: 'food-lodging',
  },
  { id: 'soup', name: '汤羹', nameEn: 'Soup', price: convertToGP(5, 'CP'), weight: 1, category: 'food-lodging' },
];

// ==================== 家庭供应 (Household Provisioning) ====================
const householdEquipment: Equipment[] = [
  { id: 'barrel-fish', name: '腌鱼桶', nameEn: 'Barrel of pickled fish', price: 3, weight: 30, category: 'household' },
  {
    id: 'butter',
    name: '黄油（每磅）',
    nameEn: 'Butter (per lb)',
    price: convertToGP(2, 'SP'),
    weight: 1,
    category: 'household',
  },
  { id: 'sugar', name: '粗糖（每磅）', nameEn: 'Coarse sugar (per lb)', price: 1, weight: 1, category: 'household' },
  {
    id: 'dry-rations',
    name: '干粮（每周）',
    nameEn: 'Dry rations (weekly)',
    price: 10,
    weight: 7,
    category: 'household',
  },
  {
    id: 'eggs-100',
    name: '鸡蛋（每100枚）',
    nameEn: 'Eggs (per 100)',
    price: convertToGP(8, 'SP'),
    weight: 8,
    category: 'household',
  },
  {
    id: 'eggs-24',
    name: '鸡蛋（两打）',
    nameEn: 'Eggs (two dozen)',
    price: convertToGP(2, 'SP'),
    weight: 2,
    category: 'household',
  },
  {
    id: 'figs',
    name: '无花果（每磅）',
    nameEn: 'Figs (per lb)',
    price: convertToGP(3, 'SP'),
    weight: 1,
    category: 'household',
  },
  {
    id: 'firewood',
    name: '柴火（每天）',
    nameEn: 'Firewood (daily)',
    price: convertToGP(1, 'CP'),
    weight: 20,
    category: 'household',
  },
  {
    id: 'herbs',
    name: '香草（每磅）',
    nameEn: 'Herbs (per lb)',
    price: convertToGP(5, 'CP'),
    weight: 1,
    category: 'household',
  },
  { id: 'nuts', name: '坚果（每磅）', nameEn: 'Nuts (per lb)', price: 1, weight: 1, category: 'household' },
  {
    id: 'raisins',
    name: '葡萄干（每磅）',
    nameEn: 'Raisins (per lb)',
    price: convertToGP(2, 'SP'),
    weight: 1,
    category: 'household',
  },
  {
    id: 'rice',
    name: '大米（每磅）',
    nameEn: 'Rice (per lb)',
    price: convertToGP(2, 'SP'),
    weight: 1,
    category: 'household',
  },
  {
    id: 'salt',
    name: '盐巴（每磅）',
    nameEn: 'Salt (per lb)',
    price: convertToGP(1, 'SP'),
    weight: 1,
    category: 'household',
  },
  {
    id: 'salted-herring',
    name: '咸鲱鱼（每100条）',
    nameEn: 'Salted herring (per 100)',
    price: 1,
    weight: 10,
    category: 'household',
  },
  {
    id: 'spice-exotic',
    name: '外来香料（每磅）',
    nameEn: 'Exotic spice (per lb)',
    price: 15,
    weight: 1,
    category: 'household',
  },
  {
    id: 'spice-rare',
    name: '稀有香料（每磅）',
    nameEn: 'Rare spice (per lb)',
    price: 2,
    weight: 1,
    category: 'household',
  },
  {
    id: 'spice-uncommon',
    name: '少见香料（每磅）',
    nameEn: 'Uncommon spice (per lb)',
    price: 1,
    weight: 1,
    category: 'household',
  },
  {
    id: 'cider-tun',
    name: '一桶果酒（250加仑）',
    nameEn: 'Tun of cider (250 gal)',
    price: 8,
    weight: 2000,
    category: 'household',
  },
  {
    id: 'wine-tun',
    name: '一桶佳酿（250加仑）',
    nameEn: 'Tun of wine (250 gal)',
    price: 20,
    weight: 2000,
    category: 'household',
  },
];

// ==================== 运输 (Transport) ====================
const transportEquipment: Equipment[] = [
  {
    id: 'barge',
    name: '驳船',
    nameEn: 'Barge',
    price: 500,
    weight: 0,
    category: 'transport',
    description: '大型水上运输工具',
  },
  { id: 'canoe-small', name: '小型轻舟', nameEn: 'Small Canoe', price: 30, weight: 50, category: 'transport' },
  { id: 'canoe-war', name: '战争轻舟', nameEn: 'War Canoe', price: 50, weight: 80, category: 'transport' },
  {
    id: 'caravel',
    name: '轻快帆船',
    nameEn: 'Caravel',
    price: 10000,
    weight: 0,
    category: 'transport',
    description: '中世纪晚期航船',
  },
  {
    id: 'carriage-common',
    name: '普通马车',
    nameEn: 'Common Carriage',
    price: 150,
    weight: 600,
    category: 'transport',
  },
  { id: 'carriage-coach', name: '长途或豪华马车', nameEn: 'Coach', price: 7000, weight: 800, category: 'transport' },
  { id: 'chariot-riding', name: '骑乘战车', nameEn: 'Riding Chariot', price: 200, weight: 400, category: 'transport' },
  { id: 'chariot-war', name: '战斗战车', nameEn: 'War Chariot', price: 500, weight: 500, category: 'transport' },
  { id: 'coaster', name: '沿海航船', nameEn: 'Coaster', price: 5000, weight: 0, category: 'transport' },
  { id: 'cog', name: '柯克船', nameEn: 'Cog', price: 10000, weight: 0, category: 'transport' },
  { id: 'curragh', name: '库拉赫', nameEn: 'Curragh', price: 500, weight: 0, category: 'transport' },
  { id: 'drakkar', name: '龙头战船', nameEn: 'Drakkar', price: 25000, weight: 0, category: 'transport' },
  { id: 'dromond', name: '快速帆船', nameEn: 'Dromond', price: 15000, weight: 0, category: 'transport' },
  { id: 'galleon', name: '盖伦船', nameEn: 'Galleon', price: 50000, weight: 0, category: 'transport' },
  { id: 'great-galley', name: '大型桨帆船', nameEn: 'Great Galley', price: 30000, weight: 0, category: 'transport' },
  { id: 'knarr', name: '维京商船', nameEn: 'Knarr', price: 3000, weight: 0, category: 'transport' },
  { id: 'longship', name: '长船', nameEn: 'Longship', price: 10000, weight: 0, category: 'transport' },
  { id: 'oar-common', name: '普通船桨', nameEn: 'Common Oar', price: 2, weight: 10, category: 'transport' },
  { id: 'oar-galley', name: '桨帆船桨', nameEn: 'Galley Oar', price: 10, weight: 15, category: 'transport' },
  {
    id: 'raft',
    name: '木筏或小型龙骨船',
    nameEn: 'Raft/Small keelboat',
    price: 100,
    weight: 200,
    category: 'transport',
  },
  { id: 'sail', name: '风帆', nameEn: 'Sail', price: 20, weight: 30, category: 'transport' },
  { id: 'sedan-chair', name: '轿子', nameEn: 'Sedan chair', price: 100, weight: 50, category: 'transport' },
  { id: 'wagon-wheel', name: '马车/手推车车轮', nameEn: 'Wagon wheel', price: 5, weight: 20, category: 'transport' },
];

// ==================== 动物 (Animals) ====================
const animalsEquipment: Equipment[] = [
  { id: 'boar', name: '野猪', nameEn: 'Boar', price: 10, weight: 0, category: 'animals' },
  { id: 'bull', name: '公牛', nameEn: 'Bull', price: 20, weight: 0, category: 'animals' },
  { id: 'calf', name: '犊牛', nameEn: 'Calf', price: 5, weight: 0, category: 'animals' },
  { id: 'camel', name: '骆驼', nameEn: 'Camel', price: 50, weight: 0, category: 'animals' },
  { id: 'capon', name: '阉鸡', nameEn: 'Capon', price: convertToGP(3, 'CP'), weight: 0, category: 'animals' },
  { id: 'cat', name: '猫', nameEn: 'Cat', price: convertToGP(1, 'SP'), weight: 0, category: 'animals' },
  { id: 'chicken', name: '雏鸡', nameEn: 'Chicken', price: convertToGP(2, 'CP'), weight: 0, category: 'animals' },
  { id: 'cow', name: '母牛', nameEn: 'Cow', price: 10, weight: 0, category: 'animals' },
  { id: 'dog-guard', name: '守卫犬', nameEn: 'Guard Dog', price: 25, weight: 0, category: 'animals' },
  { id: 'dog-hunting', name: '狩猎犬', nameEn: 'Hunting Dog', price: 17, weight: 0, category: 'animals' },
  { id: 'dog-war', name: '战犬', nameEn: 'War Dog', price: 20, weight: 0, category: 'animals' },
  { id: 'donkey', name: '毛驴/骡子/野驴', nameEn: 'Donkey/Mule/Ass', price: 8, weight: 0, category: 'animals' },
  { id: 'elephant-labor', name: '劳作象', nameEn: 'Labor Elephant', price: 200, weight: 0, category: 'animals' },
  { id: 'elephant-war', name: '战象', nameEn: 'War Elephant', price: 500, weight: 0, category: 'animals' },
  { id: 'falcon', name: '受训猎鹰', nameEn: 'Falcon (trained)', price: 1000, weight: 0, category: 'animals' },
  { id: 'goat', name: '山羊', nameEn: 'Goat', price: 1, weight: 0, category: 'animals' },
  { id: 'goose', name: '鹅', nameEn: 'Goose', price: convertToGP(5, 'CP'), weight: 0, category: 'animals' },
  {
    id: 'guinea-hen',
    name: '雌珠鸡',
    nameEn: 'Guinea hen',
    price: convertToGP(2, 'CP'),
    weight: 0,
    category: 'animals',
  },
  { id: 'horse-draft', name: '拉车用马', nameEn: 'Draft Horse', price: 200, weight: 0, category: 'animals' },
  { id: 'horse-heavy-war', name: '重型战马', nameEn: 'Heavy War Horse', price: 400, weight: 0, category: 'animals' },
  { id: 'horse-light-war', name: '轻型战马', nameEn: 'Light War Horse', price: 150, weight: 0, category: 'animals' },
  { id: 'horse-medium-war', name: '中型战马', nameEn: 'Medium War Horse', price: 225, weight: 0, category: 'animals' },
  { id: 'horse-riding', name: '骑乘用马', nameEn: 'Riding Horse', price: 75, weight: 0, category: 'animals' },
  { id: 'hunting-cat', name: '猎猫（如美洲虎）', nameEn: 'Hunting cat', price: 5000, weight: 0, category: 'animals' },
  { id: 'ox', name: '阉牛', nameEn: 'Ox', price: 15, weight: 0, category: 'animals' },
  { id: 'partridge', name: '山鹑', nameEn: 'Partridge', price: convertToGP(5, 'CP'), weight: 0, category: 'animals' },
  { id: 'peacock', name: '雄孔雀', nameEn: 'Peacock', price: convertToGP(5, 'SP'), weight: 0, category: 'animals' },
  { id: 'pig', name: '猪', nameEn: 'Pig', price: 3, weight: 0, category: 'animals' },
  { id: 'pigeon', name: '鸽子', nameEn: 'Pigeon', price: convertToGP(1, 'CP'), weight: 0, category: 'animals' },
  { id: 'pigeon-homing', name: '信鸽', nameEn: 'Homing Pigeon', price: 100, weight: 0, category: 'animals' },
  { id: 'pony', name: '马驹', nameEn: 'Pony', price: 30, weight: 0, category: 'animals' },
  { id: 'ram', name: '公羊', nameEn: 'Ram', price: 4, weight: 0, category: 'animals' },
  { id: 'sheep', name: '绵羊', nameEn: 'Sheep', price: 2, weight: 0, category: 'animals' },
  { id: 'songbird', name: '鸣禽', nameEn: 'Songbird', price: convertToGP(10, 'SP'), weight: 0, category: 'animals' },
  { id: 'swan', name: '天鹅', nameEn: 'Swan', price: convertToGP(5, 'SP'), weight: 0, category: 'animals' },
];

// ==================== 服务 (Services) ====================
const servicesEquipment: Equipment[] = [
  { id: 'bath', name: '洗浴', nameEn: 'Bath', price: convertToGP(3, 'CP'), weight: 0, category: 'services' },
  {
    id: 'clerk',
    name: '文书（每封）',
    nameEn: 'Clerk (per letter)',
    price: convertToGP(2, 'SP'),
    weight: 0,
    category: 'services',
  },
  { id: 'doctor', name: '放血或蚂蝗疗法', nameEn: 'Doctor/Bleeding', price: 3, weight: 0, category: 'services' },
  {
    id: 'guide-city',
    name: '城市向导（每天）',
    nameEn: 'City Guide (daily)',
    price: convertToGP(2, 'SP'),
    weight: 0,
    category: 'services',
  },
  {
    id: 'lantern-bearer',
    name: '提灯人（每晚）',
    nameEn: 'Lantern bearer (nightly)',
    price: convertToGP(1, 'SP'),
    weight: 0,
    category: 'services',
  },
  {
    id: 'laundry',
    name: '洗衣（每次）',
    nameEn: 'Laundry',
    price: convertToGP(1, 'CP'),
    weight: 0,
    category: 'services',
  },
  {
    id: 'messenger',
    name: '城市信使（每条消息）',
    nameEn: 'Messenger',
    price: convertToGP(1, 'SP'),
    weight: 0,
    category: 'services',
  },
  {
    id: 'minstrel',
    name: '吟游诗人（每场）',
    nameEn: 'Minstrel (per performance)',
    price: 3,
    weight: 0,
    category: 'services',
  },
  {
    id: 'mourner',
    name: '送葬者（每场）',
    nameEn: 'Mourner (per funeral)',
    price: convertToGP(2, 'SP'),
    weight: 0,
    category: 'services',
  },
  {
    id: 'teamster',
    name: '货车车夫（含货车，每英里）',
    nameEn: 'Teamster (per mile)',
    price: convertToGP(1, 'SP'),
    weight: 0,
    category: 'services',
  },
];

// ==================== 坐骑装备 (Tack and Harness) ====================
const tackEquipment: Equipment[] = [
  { id: 'barding-chain', name: '坐骑链甲', nameEn: 'Chain Barding', price: 500, weight: 70, category: 'tack' },
  {
    id: 'barding-full-plate',
    name: '坐骑全身板甲',
    nameEn: 'Full Plate Barding',
    price: 2000,
    weight: 85,
    category: 'tack',
  },
  {
    id: 'barding-full-scale',
    name: '坐骑全身鳞甲',
    nameEn: 'Full Scale Barding',
    price: 1000,
    weight: 75,
    category: 'tack',
  },
  {
    id: 'barding-half-brigandine',
    name: '坐骑半身镶片皮甲',
    nameEn: 'Half Brigandine Barding',
    price: 500,
    weight: 45,
    category: 'tack',
  },
  {
    id: 'barding-half-padded',
    name: '坐骑半身衬甲',
    nameEn: 'Half Padded Barding',
    price: 100,
    weight: 25,
    category: 'tack',
  },
  {
    id: 'barding-half-scale',
    name: '坐骑半身鳞甲',
    nameEn: 'Half Scale Barding',
    price: 500,
    weight: 50,
    category: 'tack',
  },
  {
    id: 'barding-leather',
    name: '坐骑皮甲或衬甲',
    nameEn: 'Leather/Padded Barding',
    price: 150,
    weight: 60,
    category: 'tack',
  },
  {
    id: 'bit-bridle',
    name: '马衔和马笼头',
    nameEn: 'Bit and bridle',
    price: convertToGP(15, 'SP'),
    weight: 3,
    category: 'tack',
  },
  { id: 'cart-harness', name: '挽具', nameEn: 'Cart harness', price: 2, weight: 10, category: 'tack' },
  { id: 'halter', name: '缰绳', nameEn: 'Halter', price: convertToGP(5, 'CP'), weight: 0.5, category: 'tack' },
  { id: 'horseshoes', name: '马蹄铁', nameEn: 'Horseshoes & shoeing', price: 1, weight: 10, category: 'tack' },
  { id: 'saddle-pack', name: '运输鞍座', nameEn: 'Pack Saddle', price: 5, weight: 15, category: 'tack' },
  { id: 'saddle-riding', name: '骑乘鞍座', nameEn: 'Riding Saddle', price: 10, weight: 35, category: 'tack' },
  { id: 'saddlebags-large', name: '大型鞍袋', nameEn: 'Large Saddlebags', price: 4, weight: 8, category: 'tack' },
  { id: 'saddlebags-small', name: '小型鞍袋', nameEn: 'Small Saddlebags', price: 3, weight: 5, category: 'tack' },
  {
    id: 'saddle-blanket',
    name: '鞍座毯',
    nameEn: 'Saddle blanket',
    price: convertToGP(3, 'SP'),
    weight: 4,
    category: 'tack',
  },
  { id: 'yoke-horse', name: '马用轭', nameEn: 'Horse Yoke', price: 5, weight: 15, category: 'tack' },
  { id: 'yoke-ox', name: '牛用轭', nameEn: 'Ox Yoke', price: 3, weight: 20, category: 'tack' },
];

// ==================== 其他装备 (Miscellaneous Equipment) ====================
const miscellaneousEquipment: Equipment[] = [
  { id: 'backpack', name: '背包', nameEn: 'Backpack', price: 2, weight: 2, category: 'miscellaneous' },
  { id: 'barrel-small', name: '小桶', nameEn: 'Small Barrel', price: 2, weight: 30, category: 'miscellaneous' },
  {
    id: 'basket-large',
    name: '大型篮子',
    nameEn: 'Large Basket',
    price: convertToGP(3, 'SP'),
    weight: 1,
    category: 'miscellaneous',
  },
  {
    id: 'basket-small',
    name: '小型篮子',
    nameEn: 'Small Basket',
    price: convertToGP(5, 'CP'),
    weight: 0.5,
    category: 'miscellaneous',
  },
  { id: 'bell', name: '铃铛', nameEn: 'Bell', price: 1, weight: 0.1, category: 'miscellaneous' },
  {
    id: 'belt-pouch-large',
    name: '大型腰包',
    nameEn: 'Large Belt pouch',
    price: 1,
    weight: 1,
    category: 'miscellaneous',
  },
  {
    id: 'belt-pouch-small',
    name: '小型腰包',
    nameEn: 'Small Belt pouch',
    price: convertToGP(7, 'SP'),
    weight: 0.5,
    category: 'miscellaneous',
  },
  { id: 'block-tackle', name: '滑轮组', nameEn: 'Block and tackle', price: 5, weight: 5, category: 'miscellaneous' },
  { id: 'bolt-case', name: '螺栓扣', nameEn: 'Bolt case', price: 1, weight: 1, category: 'miscellaneous' },
  { id: 'bucket', name: '吊桶', nameEn: 'Bucket', price: convertToGP(5, 'SP'), weight: 3, category: 'miscellaneous' },
  {
    id: 'chain-heavy',
    name: '重型链条（每英尺）',
    nameEn: 'Heavy Chain (per ft)',
    price: 4,
    weight: 3,
    category: 'miscellaneous',
  },
  {
    id: 'chain-light',
    name: '轻型链条（每英尺）',
    nameEn: 'Light Chain (per ft)',
    price: 3,
    weight: 1,
    category: 'miscellaneous',
  },
  { id: 'chest-large', name: '大型木箱', nameEn: 'Large Chest', price: 2, weight: 25, category: 'miscellaneous' },
  { id: 'chest-small', name: '小型木箱', nameEn: 'Small Chest', price: 1, weight: 10, category: 'miscellaneous' },
  {
    id: 'cloth-common',
    name: '普通布料（每10平方码）',
    nameEn: 'Common Cloth (per 10 sq yd)',
    price: 7,
    weight: 10,
    category: 'miscellaneous',
  },
  {
    id: 'cloth-fine',
    name: '精制布料（每10平方码）',
    nameEn: 'Fine Cloth (per 10 sq yd)',
    price: 50,
    weight: 10,
    category: 'miscellaneous',
  },
  {
    id: 'cloth-rich',
    name: '昂贵布料（每10平方码）',
    nameEn: 'Rich Cloth (per 10 sq yd)',
    price: 100,
    weight: 10,
    category: 'miscellaneous',
  },
  { id: 'candle', name: '蜡烛', nameEn: 'Candle', price: convertToGP(1, 'CP'), weight: 0.1, category: 'miscellaneous' },
  {
    id: 'canvas',
    name: '帆布（每平方码）',
    nameEn: 'Canvas (per sq yd)',
    price: convertToGP(4, 'SP'),
    weight: 1,
    category: 'miscellaneous',
  },
  { id: 'chalk', name: '粉笔', nameEn: 'Chalk', price: convertToGP(1, 'CP'), weight: 0.1, category: 'miscellaneous' },
  { id: 'crampons', name: '钉鞋', nameEn: 'Crampons', price: 4, weight: 2, category: 'miscellaneous' },
  {
    id: 'fishhook',
    name: '鱼钩',
    nameEn: 'Fishhook',
    price: convertToGP(1, 'SP'),
    weight: 0.1,
    category: 'miscellaneous',
  },
  {
    id: 'fishing-net',
    name: '渔网（每10平方英尺）',
    nameEn: 'Fishing net (per 10 sq ft)',
    price: 4,
    weight: 5,
    category: 'miscellaneous',
  },
  {
    id: 'flint-steel',
    name: '燧石与火镰',
    nameEn: 'Flint and steel',
    price: convertToGP(5, 'SP'),
    weight: 0.5,
    category: 'miscellaneous',
  },
  { id: 'glass-bottle', name: '玻璃瓶', nameEn: 'Glass bottle', price: 10, weight: 0.5, category: 'miscellaneous' },
  {
    id: 'grappling-hook',
    name: '爪钩',
    nameEn: 'Grappling hook',
    price: convertToGP(8, 'SP'),
    weight: 4,
    category: 'miscellaneous',
  },
  {
    id: 'holy-item',
    name: '圣物（圣徽、圣水等）',
    nameEn: 'Holy item',
    price: 25,
    weight: 1,
    category: 'miscellaneous',
  },
  { id: 'hourglass', name: '沙漏', nameEn: 'Hourglass', price: 25, weight: 1, category: 'miscellaneous' },
  {
    id: 'iron-pot',
    name: '铁坩埚',
    nameEn: 'Iron pot',
    price: convertToGP(5, 'SP'),
    weight: 2,
    category: 'miscellaneous',
  },
  {
    id: 'ladder',
    name: '梯子（每10英尺）',
    nameEn: 'Ladder (per 10 ft)',
    price: convertToGP(5, 'CP'),
    weight: 20,
    category: 'miscellaneous',
  },
  { id: 'lantern-beacon', name: '信标灯', nameEn: 'Beacon Lantern', price: 150, weight: 50, category: 'miscellaneous' },
  {
    id: 'lantern-bullseye',
    name: '牛眼提灯',
    nameEn: 'Bullseye Lantern',
    price: 12,
    weight: 3,
    category: 'miscellaneous',
  },
  { id: 'lantern-hooded', name: '附盖提灯', nameEn: 'Hooded Lantern', price: 7, weight: 2, category: 'miscellaneous' },
  { id: 'lock-good', name: '良好锁', nameEn: 'Good Lock', price: 100, weight: 1, category: 'miscellaneous' },
  { id: 'lock-poor', name: '较差锁', nameEn: 'Poor Lock', price: 20, weight: 1, category: 'miscellaneous' },
  {
    id: 'magnifying-glass',
    name: '放大镜',
    nameEn: 'Magnifying glass',
    price: 100,
    weight: 0.1,
    category: 'miscellaneous',
  },
  {
    id: 'map-case',
    name: '地图或卷轴匣',
    nameEn: 'Map/scroll case',
    price: convertToGP(8, 'SP'),
    weight: 0.5,
    category: 'miscellaneous',
  },
  {
    id: 'merchant-scale',
    name: '商用天平',
    nameEn: "Merchant's scale",
    price: 2,
    weight: 1,
    category: 'miscellaneous',
  },
  {
    id: 'mirror-metal',
    name: '小型金属镜',
    nameEn: 'Small metal mirror',
    price: 10,
    weight: 0.5,
    category: 'miscellaneous',
  },
  {
    id: 'musical-instrument',
    name: '乐器',
    nameEn: 'Musical instrument',
    price: 50,
    weight: 2,
    category: 'miscellaneous',
    description: '价格5-100gp，重量0.5-3磅',
  },
  {
    id: 'oil-greek-fire',
    name: '希腊火（每瓶）',
    nameEn: 'Greek fire (per flask)',
    price: 10,
    weight: 2,
    category: 'miscellaneous',
  },
  {
    id: 'oil-lamp',
    name: '灯油（每瓶）',
    nameEn: 'Lamp oil (per flask)',
    price: convertToGP(6, 'CP'),
    weight: 1,
    category: 'miscellaneous',
  },
  { id: 'paper', name: '纸张（每张）', nameEn: 'Paper (per sheet)', price: 2, weight: 0.01, category: 'miscellaneous' },
  {
    id: 'papyrus',
    name: '莎草纸（每张）',
    nameEn: 'Papyrus (per sheet)',
    price: convertToGP(8, 'SP'),
    weight: 0.01,
    category: 'miscellaneous',
  },
  {
    id: 'parchment',
    name: '羊皮纸（每张）',
    nameEn: 'Parchment (per sheet)',
    price: 1,
    weight: 0.01,
    category: 'miscellaneous',
  },
  {
    id: 'perfume',
    name: '香水（每瓶）',
    nameEn: 'Perfume (per vial)',
    price: 5,
    weight: 0.1,
    category: 'miscellaneous',
  },
  { id: 'piton', name: '岩钉', nameEn: 'Piton', price: convertToGP(3, 'CP'), weight: 0.5, category: 'miscellaneous' },
  { id: 'quiver', name: '箭袋', nameEn: 'Quiver', price: convertToGP(8, 'SP'), weight: 1, category: 'miscellaneous' },
  {
    id: 'rope-hemp',
    name: '麻绳（每50英尺）',
    nameEn: 'Hemp Rope (per 50 ft)',
    price: 1,
    weight: 20,
    category: 'miscellaneous',
  },
  {
    id: 'rope-silk',
    name: '丝绳（每50英尺）',
    nameEn: 'Silk Rope (per 50 ft)',
    price: 10,
    weight: 8,
    category: 'miscellaneous',
  },
  {
    id: 'sack-large',
    name: '大型麻袋',
    nameEn: 'Large Sack',
    price: convertToGP(2, 'SP'),
    weight: 0.5,
    category: 'miscellaneous',
  },
  {
    id: 'sack-small',
    name: '小型麻袋',
    nameEn: 'Small Sack',
    price: convertToGP(5, 'CP'),
    weight: 0.2,
    category: 'miscellaneous',
  },
  {
    id: 'sealing-wax',
    name: '火漆或蜡油（每磅）',
    nameEn: 'Sealing wax (per lb)',
    price: 1,
    weight: 1,
    category: 'miscellaneous',
  },
  {
    id: 'sewing-needle',
    name: '缝衣针',
    nameEn: 'Sewing needle',
    price: convertToGP(5, 'SP'),
    weight: 0.01,
    category: 'miscellaneous',
  },
  {
    id: 'signal-whistle',
    name: '信号哨',
    nameEn: 'Signal whistle',
    price: convertToGP(8, 'SP'),
    weight: 0.1,
    category: 'miscellaneous',
  },
  { id: 'signet-ring', name: '印戒或私章', nameEn: 'Signet ring', price: 5, weight: 0.1, category: 'miscellaneous' },
  {
    id: 'soap',
    name: '肥皂（每磅）',
    nameEn: 'Soap (per lb)',
    price: convertToGP(5, 'SP'),
    weight: 1,
    category: 'miscellaneous',
  },
  { id: 'spyglass', name: '望远镜', nameEn: 'Spyglass', price: 1000, weight: 1, category: 'miscellaneous' },
  { id: 'tent-large', name: '大帐篷', nameEn: 'Large Tent', price: 25, weight: 20, category: 'miscellaneous' },
  { id: 'tent-pavilion', name: '旅行帐篷', nameEn: 'Pavilion Tent', price: 100, weight: 50, category: 'miscellaneous' },
  { id: 'tent-small', name: '小帐篷', nameEn: 'Small Tent', price: 5, weight: 10, category: 'miscellaneous' },
  { id: 'thieves-picks', name: '盗贼工具', nameEn: "Thieves' picks", price: 30, weight: 1, category: 'miscellaneous' },
  { id: 'torch', name: '火炬', nameEn: 'Torch', price: convertToGP(1, 'CP'), weight: 1, category: 'miscellaneous' },
  { id: 'water-clock', name: '水钟', nameEn: 'Water clock', price: 1000, weight: 200, category: 'miscellaneous' },
  {
    id: 'whetstone',
    name: '磨刀石',
    nameEn: 'Whetstone',
    price: convertToGP(2, 'CP'),
    weight: 1,
    category: 'miscellaneous',
  },
  {
    id: 'wineskin',
    name: '水袋',
    nameEn: 'Wineskin',
    price: convertToGP(8, 'SP'),
    weight: 1,
    category: 'miscellaneous',
  },
  {
    id: 'winter-blanket',
    name: '冬用毛毯',
    nameEn: 'Winter blanket',
    price: convertToGP(5, 'SP'),
    weight: 3,
    category: 'miscellaneous',
  },
  {
    id: 'writing-ink',
    name: '墨水（每瓶）',
    nameEn: 'Writing ink (per vial)',
    price: 8,
    weight: 0.1,
    category: 'miscellaneous',
  },
];

// ==================== 护甲 (Armor) ====================
const armorEquipment: Armor[] = [
  {
    id: 'banded-mail',
    name: '带甲',
    nameEn: 'Banded mail',
    price: 200,
    weight: 35,
    category: 'armor',
    ac: 4,
    armorType: 'heavy',
  },
  {
    id: 'brigandine',
    name: '镶片皮甲',
    nameEn: 'Brigandine',
    price: 120,
    weight: 35,
    category: 'armor',
    ac: 6,
    armorType: 'medium',
  },
  {
    id: 'bronze-plate',
    name: '青铜板甲',
    nameEn: 'Bronze plate mail',
    price: 400,
    weight: 45,
    category: 'armor',
    ac: 4,
    armorType: 'heavy',
  },
  {
    id: 'chain-mail',
    name: '链甲',
    nameEn: 'Chain mail',
    price: 75,
    weight: 40,
    category: 'armor',
    ac: 5,
    armorType: 'medium',
  },
  {
    id: 'field-plate',
    name: '野战板甲',
    nameEn: 'Field plate',
    price: 2000,
    weight: 60,
    category: 'armor',
    ac: 2,
    armorType: 'heavy',
  },
  {
    id: 'full-plate',
    name: '全身板甲',
    nameEn: 'Full plate',
    price: 7000,
    weight: 70,
    category: 'armor',
    ac: 1,
    armorType: 'heavy',
    description: '价格4000-10000gp',
  },
  {
    id: 'helmet-great',
    name: '桶盔',
    nameEn: 'Great helm',
    price: 30,
    weight: 10,
    category: 'armor',
    ac: 10,
    armorType: 'light',
  },
  {
    id: 'helmet-basinet',
    name: '轻钢盔',
    nameEn: 'Basinet',
    price: 8,
    weight: 5,
    category: 'armor',
    ac: 10,
    armorType: 'light',
  },
  { id: 'hide', name: '毛皮甲', nameEn: 'Hide', price: 15, weight: 30, category: 'armor', ac: 6, armorType: 'medium' },
  {
    id: 'leather',
    name: '皮甲',
    nameEn: 'Leather',
    price: 5,
    weight: 15,
    category: 'armor',
    ac: 8,
    armorType: 'light',
  },
  { id: 'padded', name: '衬甲', nameEn: 'Padded', price: 4, weight: 10, category: 'armor', ac: 8, armorType: 'light' },
  {
    id: 'plate-mail',
    name: '板甲',
    nameEn: 'Plate mail',
    price: 600,
    weight: 50,
    category: 'armor',
    ac: 3,
    armorType: 'heavy',
  },
  {
    id: 'ring-mail',
    name: '锁环甲',
    nameEn: 'Ring mail',
    price: 100,
    weight: 30,
    category: 'armor',
    ac: 7,
    armorType: 'medium',
  },
  {
    id: 'scale-mail',
    name: '鳞甲',
    nameEn: 'Scale mail',
    price: 120,
    weight: 40,
    category: 'armor',
    ac: 6,
    armorType: 'medium',
  },
  {
    id: 'shield-body',
    name: '塔盾',
    nameEn: 'Body Shield',
    price: 10,
    weight: 15,
    category: 'armor',
    ac: 9,
    armorType: 'shield',
  },
  {
    id: 'shield-buckler',
    name: '小圆盾',
    nameEn: 'Buckler',
    price: 1,
    weight: 3,
    category: 'armor',
    ac: 9,
    armorType: 'shield',
  },
  {
    id: 'shield-medium',
    name: '中型盾牌',
    nameEn: 'Medium Shield',
    price: 7,
    weight: 10,
    category: 'armor',
    ac: 9,
    armorType: 'shield',
  },
  {
    id: 'shield-small',
    name: '小型盾牌',
    nameEn: 'Small Shield',
    price: 3,
    weight: 5,
    category: 'armor',
    ac: 9,
    armorType: 'shield',
  },
  {
    id: 'splint-mail',
    name: '板条甲',
    nameEn: 'Splint mail',
    price: 80,
    weight: 40,
    category: 'armor',
    ac: 4,
    armorType: 'heavy',
  },
  {
    id: 'studded-leather',
    name: '镶嵌皮甲',
    nameEn: 'Studded leather',
    price: 20,
    weight: 25,
    category: 'armor',
    ac: 7,
    armorType: 'light',
  },
];

// ==================== 武器 (Weapons) ====================
const weaponEquipment: Weapon[] = [
  // 远程武器
  {
    id: 'arquebus',
    name: '火绳枪',
    nameEn: 'Arquebus',
    price: 500,
    weight: 10,
    category: 'weapons',
    size: 'M',
    type: 'P',
    speed: 15,
    damageS: '1d10',
    damageL: '1d10',
    rateOfFire: '1/3',
    range: { short: 50, medium: 150, long: 210 },
  },
  {
    id: 'bow-short',
    name: '短弓',
    nameEn: 'Short bow',
    price: 30,
    weight: 2,
    category: 'weapons',
    size: 'M',
    type: 'P',
    speed: 7,
    damageS: '-',
    damageL: '-',
    rateOfFire: '2/1',
    range: { short: 50, medium: 100, long: 150 },
  },
  {
    id: 'bow-long',
    name: '长弓',
    nameEn: 'Long bow',
    price: 75,
    weight: 3,
    category: 'weapons',
    size: 'L',
    type: 'P',
    speed: 8,
    damageS: '-',
    damageL: '-',
    rateOfFire: '2/1',
    range: { short: 70, medium: 140, long: 210 },
  },
  {
    id: 'bow-composite-short',
    name: '复合短弓',
    nameEn: 'Composite short bow',
    price: 75,
    weight: 2,
    category: 'weapons',
    size: 'M',
    type: 'P',
    speed: 6,
    damageS: '-',
    damageL: '-',
    rateOfFire: '2/1',
    range: { short: 50, medium: 100, long: 180 },
  },
  {
    id: 'bow-composite-long',
    name: '复合长弓',
    nameEn: 'Composite long bow',
    price: 100,
    weight: 3,
    category: 'weapons',
    size: 'L',
    type: 'P',
    speed: 7,
    damageS: '-',
    damageL: '-',
    rateOfFire: '2/1',
    range: { short: 60, medium: 120, long: 210 },
  },
  {
    id: 'arrow-flight',
    name: '猎箭（12支）',
    nameEn: 'Flight arrow (12)',
    price: convertToGP(3, 'SP'),
    weight: 1,
    category: 'weapons',
    size: 'S',
    type: 'P',
    speed: 0,
    damageS: '1d6',
    damageL: '1d6',
  },
  {
    id: 'arrow-sheaf',
    name: '束箭（6支）',
    nameEn: 'Sheaf arrow (6)',
    price: convertToGP(3, 'SP'),
    weight: 1,
    category: 'weapons',
    size: 'S',
    type: 'P',
    speed: 0,
    damageS: '1d8',
    damageL: '1d8',
  },
  {
    id: 'crossbow-hand',
    name: '手弩',
    nameEn: 'Hand crossbow',
    price: 300,
    weight: 3,
    category: 'weapons',
    size: 'S',
    type: 'P',
    speed: 5,
    damageS: '-',
    damageL: '-',
    rateOfFire: '1/1',
    range: { short: 20, medium: 40, long: 60 },
  },
  {
    id: 'crossbow-light',
    name: '轻弩',
    nameEn: 'Light crossbow',
    price: 35,
    weight: 7,
    category: 'weapons',
    size: 'M',
    type: 'P',
    speed: 7,
    damageS: '-',
    damageL: '-',
    rateOfFire: '1/1',
    range: { short: 60, medium: 120, long: 180 },
  },
  {
    id: 'crossbow-heavy',
    name: '重弩',
    nameEn: 'Heavy crossbow',
    price: 50,
    weight: 14,
    category: 'weapons',
    size: 'M',
    type: 'P',
    speed: 10,
    damageS: '-',
    damageL: '-',
    rateOfFire: '1/2',
    range: { short: 80, medium: 160, long: 240 },
  },
  {
    id: 'quarrel-hand',
    name: '手弩矢',
    nameEn: 'Hand quarrel',
    price: 1,
    weight: 0.1,
    category: 'weapons',
    size: 'S',
    type: 'P',
    speed: 0,
    damageS: '1d3',
    damageL: '1d2',
  },
  {
    id: 'quarrel-light',
    name: '轻弩矢',
    nameEn: 'Light quarrel',
    price: convertToGP(1, 'SP'),
    weight: 0.1,
    category: 'weapons',
    size: 'S',
    type: 'P',
    speed: 0,
    damageS: '1d4',
    damageL: '1d4',
  },
  {
    id: 'quarrel-heavy',
    name: '重弩矢',
    nameEn: 'Heavy quarrel',
    price: convertToGP(2, 'SP'),
    weight: 0.1,
    category: 'weapons',
    size: 'S',
    type: 'P',
    speed: 0,
    damageS: '1d4+1',
    damageL: '1d6+1',
  },
  {
    id: 'blowgun',
    name: '吹筒武器',
    nameEn: 'Blowgun',
    price: 5,
    weight: 2,
    category: 'weapons',
    size: 'L',
    type: 'P',
    speed: 5,
    damageS: '-',
    damageL: '-',
    rateOfFire: '2/1',
    range: { short: 10, medium: 20, long: 30 },
  },
  {
    id: 'dart-barbed',
    name: '吹箭',
    nameEn: 'Barbed dart',
    price: convertToGP(1, 'SP'),
    weight: 0.1,
    category: 'weapons',
    size: 'S',
    type: 'P',
    speed: 0,
    damageS: '1d3',
    damageL: '1d2',
  },
  {
    id: 'dart-needle',
    name: '吹针',
    nameEn: 'Needle',
    price: convertToGP(2, 'CP'),
    weight: 0.01,
    category: 'weapons',
    size: 'S',
    type: 'P',
    speed: 0,
    damageS: '1',
    damageL: '1',
  },
  {
    id: 'dart',
    name: '飞镖',
    nameEn: 'Dart',
    price: convertToGP(5, 'SP'),
    weight: 0.5,
    category: 'weapons',
    size: 'S',
    type: 'P',
    speed: 2,
    damageS: '1d3',
    damageL: '1d2',
    rateOfFire: '3/1',
    range: { short: 10, medium: 20, long: 40 },
  },
  {
    id: 'sling',
    name: '投索',
    nameEn: 'Sling',
    price: convertToGP(5, 'CP'),
    weight: 0.1,
    category: 'weapons',
    size: 'S',
    type: 'B',
    speed: 6,
    damageS: '-',
    damageL: '-',
    rateOfFire: '1/1',
    range: { short: 40, medium: 80, long: 160 },
  },
  {
    id: 'sling-bullet',
    name: '弹丸',
    nameEn: 'Sling bullet',
    price: convertToGP(1, 'CP'),
    weight: 0.1,
    category: 'weapons',
    size: 'S',
    type: 'B',
    speed: 0,
    damageS: '1d4+1',
    damageL: '1d6+1',
  },
  {
    id: 'sling-stone',
    name: '投石',
    nameEn: 'Sling stone',
    price: 0,
    weight: 0.1,
    category: 'weapons',
    size: 'S',
    type: 'B',
    speed: 0,
    damageS: '1d4',
    damageL: '1d4',
  },

  // 近战武器
  {
    id: 'battle-axe',
    name: '战斧',
    nameEn: 'Battle axe',
    price: 5,
    weight: 7,
    category: 'weapons',
    size: 'M',
    type: 'S',
    speed: 7,
    damageS: '1d8',
    damageL: '1d8',
  },
  {
    id: 'club',
    name: '木棒',
    nameEn: 'Club',
    price: 0,
    weight: 3,
    category: 'weapons',
    size: 'M',
    type: 'B',
    speed: 4,
    damageS: '1d6',
    damageL: '1d3',
  },
  {
    id: 'dagger',
    name: '匕首或长匕首',
    nameEn: 'Dagger/Dirk',
    price: 2,
    weight: 1,
    category: 'weapons',
    size: 'S',
    type: 'P',
    speed: 2,
    damageS: '1d4',
    damageL: '1d3',
    rateOfFire: '2/1',
    range: { short: 10, medium: 20, long: 30 },
  },
  {
    id: 'flail-footman',
    name: '步兵连枷',
    nameEn: "Footman's flail",
    price: 15,
    weight: 15,
    category: 'weapons',
    size: 'M',
    type: 'B',
    speed: 7,
    damageS: '1d6+1',
    damageL: '2d4',
  },
  {
    id: 'mace-footman',
    name: '步兵硬头锤',
    nameEn: "Footman's mace",
    price: 8,
    weight: 10,
    category: 'weapons',
    size: 'M',
    type: 'B',
    speed: 7,
    damageS: '1d6+1',
    damageL: '1d6',
  },
  {
    id: 'pick-footman',
    name: '步兵镐',
    nameEn: "Footman's pick",
    price: 8,
    weight: 6,
    category: 'weapons',
    size: 'M',
    type: 'P',
    speed: 7,
    damageS: '1d6+1',
    damageL: '2d4',
  },
  {
    id: 'axe-hand',
    name: '手斧或飞斧',
    nameEn: 'Hand/throwing axe',
    price: 1,
    weight: 5,
    category: 'weapons',
    size: 'M',
    type: 'S',
    speed: 4,
    damageS: '1d6',
    damageL: '1d4',
    rateOfFire: '1/1',
    range: { short: 10, medium: 20, long: 30 },
  },
  {
    id: 'harpoon',
    name: '鱼叉',
    nameEn: 'Harpoon',
    price: 20,
    weight: 6,
    category: 'weapons',
    size: 'L',
    type: 'P',
    speed: 7,
    damageS: '2d4',
    damageL: '2d6',
    rateOfFire: '1/1',
    range: { short: 10, medium: 20, long: 30 },
  },
  {
    id: 'flail-horseman',
    name: '骑兵连枷',
    nameEn: "Horseman's flail",
    price: 8,
    weight: 5,
    category: 'weapons',
    size: 'M',
    type: 'B',
    speed: 6,
    damageS: '1d4+1',
    damageL: '1d4+1',
  },
  {
    id: 'mace-horseman',
    name: '骑兵硬头锤',
    nameEn: "Horseman's mace",
    price: 5,
    weight: 6,
    category: 'weapons',
    size: 'M',
    type: 'B',
    speed: 6,
    damageS: '1d6',
    damageL: '1d4',
  },
  {
    id: 'pick-horseman',
    name: '骑兵镐',
    nameEn: "Horseman's pick",
    price: 7,
    weight: 4,
    category: 'weapons',
    size: 'M',
    type: 'P',
    speed: 5,
    damageS: '1d4+1',
    damageL: '1d4',
  },
  {
    id: 'javelin',
    name: '标枪',
    nameEn: 'Javelin',
    price: convertToGP(5, 'SP'),
    weight: 2,
    category: 'weapons',
    size: 'M',
    type: 'P',
    speed: 4,
    damageS: '1d6',
    damageL: '1d6',
    rateOfFire: '1/1',
    range: { short: 20, medium: 40, long: 60 },
  },
  {
    id: 'knife',
    name: '小刀',
    nameEn: 'Knife',
    price: convertToGP(5, 'SP'),
    weight: 0.5,
    category: 'weapons',
    size: 'S',
    type: 'P/S',
    speed: 2,
    damageS: '1d3',
    damageL: '1d2',
    rateOfFire: '2/1',
    range: { short: 10, medium: 20, long: 30 },
  },
  {
    id: 'lance-heavy-horse',
    name: '重型骑枪',
    nameEn: 'Heavy horse lance',
    price: 15,
    weight: 15,
    category: 'weapons',
    size: 'L',
    type: 'P',
    speed: 8,
    damageS: '1d8+1',
    damageL: '3d6',
  },
  {
    id: 'lance-light-horse',
    name: '轻型骑枪',
    nameEn: 'Light horse lance',
    price: 6,
    weight: 5,
    category: 'weapons',
    size: 'L',
    type: 'P',
    speed: 6,
    damageS: '1d6',
    damageL: '1d8',
  },
  {
    id: 'lance-jousting',
    name: '比武用骑枪',
    nameEn: 'Jousting lance',
    price: 20,
    weight: 20,
    category: 'weapons',
    size: 'L',
    type: 'P',
    speed: 10,
    damageS: '1d3-1',
    damageL: '1d2-1',
  },
  {
    id: 'lance-medium-horse',
    name: '中型骑枪',
    nameEn: 'Medium horse lance',
    price: 10,
    weight: 10,
    category: 'weapons',
    size: 'L',
    type: 'P',
    speed: 7,
    damageS: '1d6+1',
    damageL: '2d6',
  },
  {
    id: 'mancatcher',
    name: '捕人叉',
    nameEn: 'Mancatcher',
    price: 30,
    weight: 8,
    category: 'weapons',
    size: 'L',
    type: 'P',
    speed: 7,
    damageS: '-',
    damageL: '-',
  },
  {
    id: 'morning-star',
    name: '晨星锤',
    nameEn: 'Morning star',
    price: 10,
    weight: 12,
    category: 'weapons',
    size: 'M',
    type: 'P/B',
    speed: 7,
    damageS: '2d4',
    damageL: '1d6+1',
  },

  // 长柄武器
  {
    id: 'awl-pike',
    name: '锥枪',
    nameEn: 'Awl pike',
    price: 5,
    weight: 12,
    category: 'weapons',
    size: 'L',
    type: 'P',
    speed: 13,
    damageS: '1d6',
    damageL: '1d12',
  },
  {
    id: 'bardiche',
    name: '长柄砍刀',
    nameEn: 'Bardiche',
    price: 7,
    weight: 12,
    category: 'weapons',
    size: 'L',
    type: 'S',
    speed: 9,
    damageS: '2d4',
    damageL: '2d6',
  },
  {
    id: 'bec-de-corbin',
    name: '鸦啄战锤',
    nameEn: 'Bec de corbin',
    price: 8,
    weight: 10,
    category: 'weapons',
    size: 'L',
    type: 'P/B',
    speed: 9,
    damageS: '1d8',
    damageL: '1d6',
  },
  {
    id: 'bill-guisarme',
    name: '倒钩戟',
    nameEn: 'Bill-guisarme',
    price: 7,
    weight: 15,
    category: 'weapons',
    size: 'L',
    type: 'P/S',
    speed: 10,
    damageS: '2d4',
    damageL: '1d10',
  },
  {
    id: 'fauchard',
    name: '战镰',
    nameEn: 'Fauchard',
    price: 5,
    weight: 7,
    category: 'weapons',
    size: 'L',
    type: 'P/S',
    speed: 8,
    damageS: '1d6',
    damageL: '1d8',
  },
  {
    id: 'glaive',
    name: '长柄宽刃刀',
    nameEn: 'Glaive',
    price: 6,
    weight: 8,
    category: 'weapons',
    size: 'L',
    type: 'S',
    speed: 8,
    damageS: '1d6',
    damageL: '1d10',
  },
  {
    id: 'guisarme',
    name: '战戟',
    nameEn: 'Guisarme',
    price: 5,
    weight: 8,
    category: 'weapons',
    size: 'L',
    type: 'S',
    speed: 8,
    damageS: '2d4',
    damageL: '1d8',
  },
  {
    id: 'halberd',
    name: '长戟',
    nameEn: 'Halberd',
    price: 10,
    weight: 15,
    category: 'weapons',
    size: 'L',
    type: 'P/S',
    speed: 9,
    damageS: '1d10',
    damageL: '2d6',
  },
  {
    id: 'lucern-hammer',
    name: '苜蓿战锤',
    nameEn: 'Lucern hammer',
    price: 7,
    weight: 15,
    category: 'weapons',
    size: 'L',
    type: 'P/B',
    speed: 9,
    damageS: '2d4',
    damageL: '1d6',
  },
  {
    id: 'military-fork',
    name: '军用叉矛',
    nameEn: 'Military fork',
    price: 5,
    weight: 7,
    category: 'weapons',
    size: 'L',
    type: 'P',
    speed: 7,
    damageS: '1d8',
    damageL: '2d4',
  },
  {
    id: 'partisan',
    name: '牛舌枪',
    nameEn: 'Partisan',
    price: 10,
    weight: 8,
    category: 'weapons',
    size: 'L',
    type: 'P',
    speed: 9,
    damageS: '1d6',
    damageL: '1d6+1',
  },
  {
    id: 'ranseur',
    name: '枪矛',
    nameEn: 'Ranseur',
    price: 6,
    weight: 7,
    category: 'weapons',
    size: 'L',
    type: 'P',
    speed: 8,
    damageS: '2d4',
    damageL: '2d4',
  },
  {
    id: 'spetum',
    name: '三叉矛',
    nameEn: 'Spetum',
    price: 5,
    weight: 7,
    category: 'weapons',
    size: 'L',
    type: 'P',
    speed: 8,
    damageS: '1d6+1',
    damageL: '2d6',
  },
  {
    id: 'voulge',
    name: '长杆宽刃戟',
    nameEn: 'Voulge',
    price: 5,
    weight: 15,
    category: 'weapons',
    size: 'L',
    type: 'S',
    speed: 10,
    damageS: '2d4',
    damageL: '2d4',
  },

  {
    id: 'quarterstaff',
    name: '铁头棍',
    nameEn: 'Quarterstaff',
    price: 0,
    weight: 4,
    category: 'weapons',
    size: 'L',
    type: 'B',
    speed: 4,
    damageS: '1d6',
    damageL: '1d6',
  },
  {
    id: 'scourge',
    name: '刑鞭',
    nameEn: 'Scourge',
    price: 1,
    weight: 2,
    category: 'weapons',
    size: 'S',
    type: 'P',
    speed: 5,
    damageS: '1d4',
    damageL: '1d2',
  },
  {
    id: 'sickle',
    name: '镰刀',
    nameEn: 'Sickle',
    price: convertToGP(6, 'SP'),
    weight: 3,
    category: 'weapons',
    size: 'S',
    type: 'S',
    speed: 4,
    damageS: '1d4+1',
    damageL: '1d4',
  },
  {
    id: 'spear',
    name: '矛',
    nameEn: 'Spear',
    price: convertToGP(8, 'SP'),
    weight: 5,
    category: 'weapons',
    size: 'M',
    type: 'P',
    speed: 6,
    damageS: '1d6',
    damageL: '1d8',
    rateOfFire: '1/1',
    range: { short: 10, medium: 20, long: 30 },
  },

  // 剑类
  {
    id: 'sword-bastard',
    name: '混种剑',
    nameEn: 'Bastard sword',
    price: 25,
    weight: 10,
    category: 'weapons',
    size: 'M',
    type: 'S',
    speed: 6,
    damageS: '1d8',
    damageL: '1d12',
    description: '可单手或双手使用',
    versatile: {
      '1H': { speed: 6, damageS: '1d8', damageL: '1d12' },
      '2H': { speed: 8, damageS: '2d4', damageL: '2d8' },
    },
  },
  {
    id: 'sword-broad',
    name: '阔剑',
    nameEn: 'Broad sword',
    price: 10,
    weight: 4,
    category: 'weapons',
    size: 'M',
    type: 'S',
    speed: 5,
    damageS: '2d4',
    damageL: '1d6+1',
  },
  {
    id: 'sword-khopesh',
    name: '镰剑',
    nameEn: 'Khopesh',
    price: 10,
    weight: 7,
    category: 'weapons',
    size: 'M',
    type: 'S',
    speed: 9,
    damageS: '2d4',
    damageL: '1d6',
  },
  {
    id: 'sword-long',
    name: '长剑',
    nameEn: 'Long sword',
    price: 15,
    weight: 4,
    category: 'weapons',
    size: 'M',
    type: 'S',
    speed: 5,
    damageS: '1d8',
    damageL: '1d12',
  },
  {
    id: 'sword-scimitar',
    name: '弯刀',
    nameEn: 'Scimitar',
    price: 15,
    weight: 4,
    category: 'weapons',
    size: 'M',
    type: 'S',
    speed: 5,
    damageS: '1d8',
    damageL: '1d8',
  },
  {
    id: 'sword-short',
    name: '短剑',
    nameEn: 'Short sword',
    price: 10,
    weight: 3,
    category: 'weapons',
    size: 'S',
    type: 'P',
    speed: 3,
    damageS: '1d6',
    damageL: '1d8',
  },
  {
    id: 'sword-two-handed',
    name: '双手剑',
    nameEn: 'Two-handed sword',
    price: 50,
    weight: 15,
    category: 'weapons',
    size: 'L',
    type: 'S',
    speed: 10,
    damageS: '1d10',
    damageL: '3d6',
  },

  {
    id: 'trident',
    name: '三叉戟',
    nameEn: 'Trident',
    price: 15,
    weight: 5,
    category: 'weapons',
    size: 'L',
    type: 'P',
    speed: 7,
    damageS: '1d6+1',
    damageL: '3d4',
  },
  {
    id: 'warhammer',
    name: '战锤',
    nameEn: 'Warhammer',
    price: 2,
    weight: 6,
    category: 'weapons',
    size: 'M',
    type: 'B',
    speed: 4,
    damageS: '1d4+1',
    damageL: '1d4',
  },
  {
    id: 'whip',
    name: '鞭子',
    nameEn: 'Whip',
    price: convertToGP(1, 'SP'),
    weight: 2,
    category: 'weapons',
    size: 'M',
    type: 'P',
    speed: 8,
    damageS: '1d2',
    damageL: '1',
  },
];

export const EQUIPMENT_DATA = {
  clothing: clothingEquipment,
  'food-lodging': foodLodgingEquipment,
  household: householdEquipment,
  transport: transportEquipment,
  animals: animalsEquipment,
  services: servicesEquipment,
  tack: tackEquipment,
  miscellaneous: miscellaneousEquipment,
  armor: armorEquipment,
  weapons: weaponEquipment,
};

// 获取指定类别的装备
export function getEquipmentByCategory(categoryId: string): Equipment[] {
  return EQUIPMENT_DATA[categoryId as keyof typeof EQUIPMENT_DATA] || [];
}

// 根据ID获取装备
export function getEquipmentById(id: string): Equipment | undefined {
  for (const category of Object.values(EQUIPMENT_DATA)) {
    const item = category.find(eq => eq.id === id);
    if (item) return item;
  }
  return undefined;
}

// 搜索装备
export function searchEquipment(query: string, categoryId?: string): Equipment[] {
  const lowerQuery = query.toLowerCase();
  const categories = categoryId
    ? [EQUIPMENT_DATA[categoryId as keyof typeof EQUIPMENT_DATA]]
    : Object.values(EQUIPMENT_DATA);

  return categories
    .flat()
    .filter(eq => eq.name.toLowerCase().includes(lowerQuery) || eq.nameEn?.toLowerCase().includes(lowerQuery));
}
