// 武器类型
export type WeaponType = 'B' | 'P' | 'S' | 'P/B' | 'P/S'; // 钝击/穿刺/挥砍

// 武器尺寸
export type WeaponSize = 'S' | 'M' | 'L';

// 武器接口
export interface Weapon {
  id: string;
  name: string;
  englishName: string;
  category: string; // 用于分组显示
  type: WeaponType;
  size: WeaponSize;
  speedFactor: number;
  damageS_M: string; // 对小型/中型生物伤害
  damageL: string; // 对大型生物伤害
  price: string;
  weight: number;
  specialNotes?: string; // 特殊说明
  relatedCategory?: string; // 相关武器分类（用于相关武器奖励）
  isAmmunition?: boolean; // 是否为弹药（弹药不需要熟练）
}

// 相关武器分类（用于-1惩罚而非全惩罚）
export const RELATED_WEAPON_CATEGORIES = {
  axes: ['hand-axe', 'battle-axe'],
  bows: ['short-bow', 'long-bow', 'composite-short-bow', 'composite-long-bow'],
  crossbows: ['hand-crossbow', 'light-crossbow', 'heavy-crossbow'],
  daggers: ['dagger', 'knife'],
  polearms: [
    'glaive',
    'halberd',
    'bardiche',
    'voulge',
    'guisarme',
    'glaive-guisarme',
    'bill-guisarme',
    'guisarme-voulge',
  ],
  spears: ['harpoon', 'spear', 'trident', 'javelin'],
  flails: ['footmans-flail', 'horsemans-flail', 'morning-star', 'footmans-mace', 'warhammer'],
  forks: ['military-fork', 'ranseur', 'spetum', 'partisan'],
  swords: ['bastard-sword', 'broad-sword', 'khopesh', 'long-sword', 'scimitar', 'short-sword', 'two-handed-sword'],
  slings: ['sling', 'staff-sling'],
};

// 武器数据（基于表44）
export const WEAPONS: Weapon[] = [
  // ==================== 弓类 ====================
  {
    id: 'short-bow',
    name: '短弓',
    englishName: 'Short Bow',
    category: '弓',
    type: 'P',
    size: 'M',
    speedFactor: 7,
    damageS_M: '1d6',
    damageL: '1d6',
    price: '30GP',
    weight: 2,
    relatedCategory: 'bows',
  },
  {
    id: 'long-bow',
    name: '长弓',
    englishName: 'Long Bow',
    category: '弓',
    type: 'P',
    size: 'L',
    speedFactor: 8,
    damageS_M: '1d6',
    damageL: '1d6',
    price: '75GP',
    weight: 3,
    relatedCategory: 'bows',
  },
  {
    id: 'composite-short-bow',
    name: '复合短弓',
    englishName: 'Composite Short Bow',
    category: '弓',
    type: 'P',
    size: 'M',
    speedFactor: 6,
    damageS_M: '1d6',
    damageL: '1d6',
    price: '75GP',
    weight: 2,
    relatedCategory: 'bows',
  },
  {
    id: 'composite-long-bow',
    name: '复合长弓',
    englishName: 'Composite Long Bow',
    category: '弓',
    type: 'P',
    size: 'L',
    speedFactor: 7,
    damageS_M: '1d6',
    damageL: '1d6',
    price: '100GP',
    weight: 3,
    relatedCategory: 'bows',
  },
  {
    id: 'flight-arrow',
    name: '猎箭',
    englishName: 'Flight Arrow',
    category: '弓箭',
    type: 'P',
    size: 'S',
    speedFactor: 0,
    damageS_M: '1d6',
    damageL: '1d6',
    price: '3SP/12',
    weight: 0,
    isAmmunition: true, // 弹药不需要熟练
  },
  {
    id: 'sheaf-arrow',
    name: '束箭',
    englishName: 'Sheaf Arrow',
    category: '弓箭',
    type: 'P',
    size: 'S',
    speedFactor: 0,
    damageS_M: '1d8',
    damageL: '1d8',
    price: '3SP/6',
    weight: 0,
    isAmmunition: true, // 弹药不需要熟练
  },

  // ==================== 弩类 ====================
  {
    id: 'hand-crossbow',
    name: '手弩',
    englishName: 'Hand Crossbow',
    category: '弩',
    type: 'P',
    size: 'S',
    speedFactor: 5,
    damageS_M: '1d3',
    damageL: '1d2',
    price: '300GP',
    weight: 3,
    relatedCategory: 'crossbows',
  },
  {
    id: 'light-crossbow',
    name: '轻弩',
    englishName: 'Light Crossbow',
    category: '弩',
    type: 'P',
    size: 'M',
    speedFactor: 7,
    damageS_M: '1d4',
    damageL: '1d4',
    price: '35GP',
    weight: 7,
    relatedCategory: 'crossbows',
  },
  {
    id: 'heavy-crossbow',
    name: '重弩',
    englishName: 'Heavy Crossbow',
    category: '弩',
    type: 'P',
    size: 'M',
    speedFactor: 10,
    damageS_M: '1d4+1',
    damageL: '1d6+1',
    price: '50GP',
    weight: 14,
    relatedCategory: 'crossbows',
  },
  {
    id: 'hand-quarrel',
    name: '手弩矢',
    englishName: 'Hand Quarrel',
    category: '弩矢',
    type: 'P',
    size: 'S',
    speedFactor: 0,
    damageS_M: '1d3',
    damageL: '1d2',
    price: '1GP',
    weight: 0,
    isAmmunition: true, // 弹药不需要熟练
  },
  {
    id: 'light-quarrel',
    name: '轻弩矢',
    englishName: 'Light Quarrel',
    category: '弩矢',
    type: 'P',
    size: 'S',
    speedFactor: 0,
    damageS_M: '1d4',
    damageL: '1d4',
    price: '1SP',
    weight: 0,
    isAmmunition: true, // 弹药不需要熟练
  },
  {
    id: 'heavy-quarrel',
    name: '重弩矢',
    englishName: 'Heavy Quarrel',
    category: '弩矢',
    type: 'P',
    size: 'S',
    speedFactor: 0,
    damageS_M: '1d4+1',
    damageL: '1d6+1',
    price: '2SP',
    weight: 0,
    isAmmunition: true, // 弹药不需要熟练
  },

  // ==================== 剑类 ====================
  {
    id: 'bastard-sword',
    name: '混种剑',
    englishName: 'Bastard Sword',
    category: '剑',
    type: 'S',
    size: 'M',
    speedFactor: 6,
    damageS_M: '1d8(单手)/2d4(双手)',
    damageL: '1d12(单手)/2d8(双手)',
    price: '25GP',
    weight: 10,
    specialNotes: '可单手或双手持用',
    relatedCategory: 'swords',
  },
  {
    id: 'broad-sword',
    name: '阔剑',
    englishName: 'Broad Sword',
    category: '剑',
    type: 'S',
    size: 'M',
    speedFactor: 5,
    damageS_M: '2d4',
    damageL: '1d6+1',
    price: '10GP',
    weight: 4,
    relatedCategory: 'swords',
  },
  {
    id: 'khopesh',
    name: '镰剑',
    englishName: 'Khopesh',
    category: '剑',
    type: 'S',
    size: 'M',
    speedFactor: 9,
    damageS_M: '2d4',
    damageL: '1d6',
    price: '10GP',
    weight: 7,
    relatedCategory: 'swords',
  },
  {
    id: 'long-sword',
    name: '长剑',
    englishName: 'Long Sword',
    category: '剑',
    type: 'S',
    size: 'M',
    speedFactor: 5,
    damageS_M: '1d8',
    damageL: '1d12',
    price: '15GP',
    weight: 4,
    relatedCategory: 'swords',
  },
  {
    id: 'scimitar',
    name: '弯刀',
    englishName: 'Scimitar',
    category: '剑',
    type: 'S',
    size: 'M',
    speedFactor: 5,
    damageS_M: '1d8',
    damageL: '1d8',
    price: '15GP',
    weight: 4,
    relatedCategory: 'swords',
  },
  {
    id: 'short-sword',
    name: '短剑',
    englishName: 'Short Sword',
    category: '剑',
    type: 'P',
    size: 'S',
    speedFactor: 3,
    damageS_M: '1d6',
    damageL: '1d8',
    price: '10GP',
    weight: 3,
    relatedCategory: 'swords',
  },
  {
    id: 'two-handed-sword',
    name: '双手剑',
    englishName: 'Two-Handed Sword',
    category: '剑',
    type: 'S',
    size: 'L',
    speedFactor: 10,
    damageS_M: '1d10',
    damageL: '3d6',
    price: '50GP',
    weight: 15,
    relatedCategory: 'swords',
  },

  // ==================== 斧类 ====================
  {
    id: 'battle-axe',
    name: '战斧',
    englishName: 'Battle Axe',
    category: '斧',
    type: 'S',
    size: 'M',
    speedFactor: 7,
    damageS_M: '1d8',
    damageL: '1d8',
    price: '5GP',
    weight: 7,
    relatedCategory: 'axes',
  },
  {
    id: 'hand-axe',
    name: '手斧',
    englishName: 'Hand Axe',
    category: '斧',
    type: 'S',
    size: 'M',
    speedFactor: 4,
    damageS_M: '1d6',
    damageL: '1d4',
    price: '1GP',
    weight: 5,
    relatedCategory: 'axes',
  },

  // ==================== 匕首类 ====================
  {
    id: 'dagger',
    name: '匕首',
    englishName: 'Dagger',
    category: '匕首',
    type: 'P',
    size: 'S',
    speedFactor: 2,
    damageS_M: '1d4',
    damageL: '1d3',
    price: '2GP',
    weight: 1,
    relatedCategory: 'daggers',
  },
  {
    id: 'knife',
    name: '小刀',
    englishName: 'Knife',
    category: '匕首',
    type: 'P/S',
    size: 'S',
    speedFactor: 2,
    damageS_M: '1d3',
    damageL: '1d2',
    price: '5SP',
    weight: 0,
    relatedCategory: 'daggers',
  },

  // ==================== 连枷/钉头锤类 ====================
  {
    id: 'footmans-flail',
    name: '步兵连枷',
    englishName: "Footman's Flail",
    category: '连枷',
    type: 'B',
    size: 'M',
    speedFactor: 7,
    damageS_M: '1d6+1',
    damageL: '2d4',
    price: '15GP',
    weight: 15,
    relatedCategory: 'flails',
  },
  {
    id: 'horsemans-flail',
    name: '骑兵连枷',
    englishName: "Horseman's Flail",
    category: '连枷',
    type: 'B',
    size: 'M',
    speedFactor: 6,
    damageS_M: '1d4+1',
    damageL: '1d4+1',
    price: '8GP',
    weight: 5,
    relatedCategory: 'flails',
  },
  {
    id: 'footmans-mace',
    name: '步兵硬头锤',
    englishName: "Footman's Mace",
    category: '钉头锤',
    type: 'B',
    size: 'M',
    speedFactor: 7,
    damageS_M: '1d6+1',
    damageL: '1d6',
    price: '8GP',
    weight: 10,
    relatedCategory: 'flails',
  },
  {
    id: 'horsemans-mace',
    name: '骑兵硬头锤',
    englishName: "Horseman's Mace",
    category: '钉头锤',
    type: 'B',
    size: 'M',
    speedFactor: 6,
    damageS_M: '1d6',
    damageL: '1d4',
    price: '5GP',
    weight: 6,
    relatedCategory: 'flails',
  },
  {
    id: 'morning-star',
    name: '晨星锤',
    englishName: 'Morning Star',
    category: '钉头锤',
    type: 'P/B',
    size: 'M',
    speedFactor: 7,
    damageS_M: '2d4',
    damageL: '1d6+1',
    price: '10GP',
    weight: 12,
    relatedCategory: 'flails',
  },
  {
    id: 'warhammer',
    name: '战锤',
    englishName: 'Warhammer',
    category: '锤',
    type: 'B',
    size: 'M',
    speedFactor: 4,
    damageS_M: '1d4+1',
    damageL: '1d4',
    price: '2GP',
    weight: 6,
    relatedCategory: 'flails',
  },

  // ==================== 矛类 ====================
  {
    id: 'spear',
    name: '矛',
    englishName: 'Spear',
    category: '矛',
    type: 'P',
    size: 'M',
    speedFactor: 6,
    damageS_M: '1d6',
    damageL: '1d8',
    price: '8SP',
    weight: 5,
    relatedCategory: 'spears',
  },
  {
    id: 'javelin',
    name: '标枪',
    englishName: 'Javelin',
    category: '矛',
    type: 'P',
    size: 'M',
    speedFactor: 4,
    damageS_M: '1d6',
    damageL: '1d6',
    price: '5SP',
    weight: 2,
    relatedCategory: 'spears',
  },
  {
    id: 'trident',
    name: '三叉戟',
    englishName: 'Trident',
    category: '矛',
    type: 'P',
    size: 'L',
    speedFactor: 7,
    damageS_M: '1d6+1',
    damageL: '3d4',
    price: '15GP',
    weight: 5,
    relatedCategory: 'spears',
  },
  {
    id: 'harpoon',
    name: '鱼叉',
    englishName: 'Harpoon',
    category: '矛',
    type: 'P',
    size: 'L',
    speedFactor: 7,
    damageS_M: '2d4',
    damageL: '2d6',
    price: '20GP',
    weight: 6,
    relatedCategory: 'spears',
  },

  // ==================== 长柄武器 ====================
  {
    id: 'glaive',
    name: '长柄宽刃刀',
    englishName: 'Glaive',
    category: '长柄武器',
    type: 'S',
    size: 'L',
    speedFactor: 8,
    damageS_M: '1d6',
    damageL: '1d10',
    price: '6GP',
    weight: 8,
    specialNotes: '反骑兵冲锋双倍伤害',
    relatedCategory: 'polearms',
  },
  {
    id: 'halberd',
    name: '长戟',
    englishName: 'Halberd',
    category: '长柄武器',
    type: 'P/S',
    size: 'L',
    speedFactor: 9,
    damageS_M: '1d10',
    damageL: '2d6',
    price: '10GP',
    weight: 15,
    relatedCategory: 'polearms',
  },
  {
    id: 'bardiche',
    name: '长柄砍刀',
    englishName: 'Bardiche',
    category: '长柄武器',
    type: 'S',
    size: 'L',
    speedFactor: 9,
    damageS_M: '2d4',
    damageL: '2d6',
    price: '7GP',
    weight: 12,
    relatedCategory: 'polearms',
  },
  {
    id: 'voulge',
    name: '长杆宽刃戟',
    englishName: 'Voulge',
    category: '长柄武器',
    type: 'S',
    size: 'L',
    speedFactor: 10,
    damageS_M: '2d4',
    damageL: '2d4',
    price: '5GP',
    weight: 15,
    relatedCategory: 'polearms',
  },
  {
    id: 'guisarme',
    name: '战戟',
    englishName: 'Guisarme',
    category: '长柄武器',
    type: 'S',
    size: 'L',
    speedFactor: 8,
    damageS_M: '2d4',
    damageL: '1d8',
    price: '5GP',
    weight: 8,
    relatedCategory: 'polearms',
  },
  {
    id: 'glaive-guisarme',
    name: '刀状战戟',
    englishName: 'Glaive-Guisarme',
    category: '长柄武器',
    type: 'P/S',
    size: 'L',
    speedFactor: 9,
    damageS_M: '2d4',
    damageL: '2d6',
    price: '10GP',
    weight: 10,
    relatedCategory: 'polearms',
  },
  {
    id: 'bill-guisarme',
    name: '倒钩戟',
    englishName: 'Bill-Guisarme',
    category: '长柄武器',
    type: 'P/S',
    size: 'L',
    speedFactor: 10,
    damageS_M: '2d4',
    damageL: '1d10',
    price: '7GP',
    weight: 15,
    relatedCategory: 'polearms',
  },
  {
    id: 'guisarme-voulge',
    name: '斧状战戟',
    englishName: 'Guisarme-Voulge',
    category: '长柄武器',
    type: 'P/S',
    size: 'L',
    speedFactor: 10,
    damageS_M: '2d4',
    damageL: '2d4',
    price: '8GP',
    weight: 15,
    relatedCategory: 'polearms',
  },

  // ==================== 叉矛类 ====================
  {
    id: 'military-fork',
    name: '军用叉矛',
    englishName: 'Military Fork',
    category: '叉矛',
    type: 'P',
    size: 'L',
    speedFactor: 7,
    damageS_M: '1d8',
    damageL: '2d4',
    price: '5GP',
    weight: 7,
    specialNotes: '反骑兵冲锋双倍伤害',
    relatedCategory: 'forks',
  },
  {
    id: 'ranseur',
    name: '枪矛',
    englishName: 'Ranseur',
    category: '叉矛',
    type: 'P',
    size: 'L',
    speedFactor: 8,
    damageS_M: '2d4',
    damageL: '2d4',
    price: '6GP',
    weight: 7,
    specialNotes: '稳固设置反冲锋双倍伤害',
    relatedCategory: 'forks',
  },
  {
    id: 'spetum',
    name: '三叉矛',
    englishName: 'Spetum',
    category: '叉矛',
    type: 'P',
    size: 'L',
    speedFactor: 8,
    damageS_M: '1d6+1',
    damageL: '2d6',
    price: '5GP',
    weight: 7,
    specialNotes: '稳固设置反冲锋双倍伤害',
    relatedCategory: 'forks',
  },
  {
    id: 'partisan',
    name: '牛舌枪',
    englishName: 'Partisan',
    category: '叉矛',
    type: 'P',
    size: 'L',
    speedFactor: 9,
    damageS_M: '1d6',
    damageL: '1d6+1',
    price: '10GP',
    weight: 8,
    specialNotes: '稳固设置反冲锋双倍伤害',
    relatedCategory: 'forks',
  },

  // ==================== 其他武器 ====================
  {
    id: 'club',
    name: '木棒',
    englishName: 'Club',
    category: '简易武器',
    type: 'B',
    size: 'M',
    speedFactor: 4,
    damageS_M: '1d6',
    damageL: '1d3',
    price: '-',
    weight: 3,
  },
  {
    id: 'quarterstaff',
    name: '铁头棍',
    englishName: 'Quarterstaff',
    category: '简易武器',
    type: 'B',
    size: 'L',
    speedFactor: 4,
    damageS_M: '1d6',
    damageL: '1d6',
    price: '-',
    weight: 4,
  },
  {
    id: 'dart',
    name: '飞镖',
    englishName: 'Dart',
    category: '投掷武器',
    type: 'P',
    size: 'S',
    speedFactor: 2,
    damageS_M: '1d3',
    damageL: '1d2',
    price: '5SP',
    weight: 0,
  },
  {
    id: 'sling',
    name: '投索',
    englishName: 'Sling',
    category: '投掷武器',
    type: 'B',
    size: 'S',
    speedFactor: 6,
    damageS_M: '1d4+1',
    damageL: '1d6+1',
    price: '5CP',
    weight: 0,
    relatedCategory: 'slings',
  },
  {
    id: 'staff-sling',
    name: '投物棒',
    englishName: 'Staff Sling',
    category: '投掷武器',
    type: 'B',
    size: 'M',
    speedFactor: 11,
    damageS_M: '1d4+1',
    damageL: '1d6+1',
    price: '2SP',
    weight: 2,
    relatedCategory: 'slings',
  },
  {
    id: 'whip',
    name: '鞭子',
    englishName: 'Whip',
    category: '特殊武器',
    type: 'B',
    size: 'M',
    speedFactor: 8,
    damageS_M: '1d2',
    damageL: '1',
    price: '1SP',
    weight: 2,
  },
  {
    id: 'blowgun',
    name: '吹筒武器',
    englishName: 'Blowgun',
    category: '特殊武器',
    type: 'P',
    size: 'L',
    speedFactor: 5,
    damageS_M: '1d3',
    damageL: '1d2',
    price: '5GP',
    weight: 2,
  },
];

// 工具函数

// 根据ID获取武器
export function getWeaponById(weaponId: string): Weapon | undefined {
  return WEAPONS.find(w => w.id === weaponId);
}

// 根据分类获取武器列表
export function getWeaponsByCategory(category: string): Weapon[] {
  return WEAPONS.filter(w => w.category === category);
}

// 获取所有武器分类
export function getAllWeaponCategories(): string[] {
  const categories = new Set<string>();
  WEAPONS.forEach(w => categories.add(w.category));
  return Array.from(categories).sort();
}

// 检查两个武器是否为相关武器
export function areWeaponsRelated(weaponId1: string, weaponId2: string): boolean {
  if (weaponId1 === weaponId2) return true;

  // 检查是否属于同一相关武器分类
  for (const category of Object.values(RELATED_WEAPON_CATEGORIES)) {
    if (category.includes(weaponId1) && category.includes(weaponId2)) {
      return true;
    }
  }

  return false;
}

// 获取武器的相关武器列表
export function getRelatedWeapons(weaponId: string): Weapon[] {
  const relatedIds: string[] = [];

  // 找到该武器所属的相关武器分类
  for (const category of Object.values(RELATED_WEAPON_CATEGORIES)) {
    if (category.includes(weaponId)) {
      relatedIds.push(...category.filter(id => id !== weaponId));
    }
  }

  return relatedIds.map(id => getWeaponById(id)).filter((w): w is Weapon => w !== undefined);
}
